import "./globals.css";
import "./Header"
import Header from "./Header";
import { TokenProvider } from './context/TokenContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-main_color font-noto-sans-cjk">
      <body className="mx-auto mt-1">
      <TokenProvider>
        <Header/>
        {children}
      </TokenProvider>  

      </body>
    </html>
  );
}
